# Generated by Django 5.0.6 on 2024-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100)),
                ('description_book', models.CharField(max_length=100)),
                ('author_book', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='upldfile/')),
                ('photo', models.ImageField(upload_to='photo/')),
            ],
        ),
    ]
