# Generated by Django 5.0.6 on 2024-07-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviews',
            field=models.TextField(),
        ),
    ]
